version: '3'
services:

  rabbitmq-server:
    image: rabbitmq:3.7.8-management
    container_name: rabbitmq_server
    hostname: "rabbitmq-server"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "0.0.0.0:15672:15672"
      - "0.0.0.0:5672:5672"
    labels:
      NAME: "rabbitmq-server"

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
      
  books_db:
    image: mariadb:10.3.10
    container_name: books_db
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=books_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  orders_db:
    image: mariadb:10.3.10
    container_name: orders_db
    ports:
      - 127.0.0.1:3307:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=orders_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    
  accounts_db:
    image: mariadb:10.3.10
    container_name: accounts_db
    ports:
      - 127.0.0.1:3308:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=accounts_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  ratings_db:
    image: mariadb:10.3.10
    container_name: ratings_db
    ports:
      - 127.0.0.1:3309:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=ratings_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
